// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNS6I9F7hGdzjYPr1o5iBCSwWgjUQn0o',
    appId: '1:593840566794:web:1b4b9cc6e8679cf35665f3',
    messagingSenderId: '593840566794',
    projectId: 'yello-18a1e',
    authDomain: 'yello-18a1e.firebaseapp.com',
    storageBucket: 'yello-18a1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDXTRF_f0FsWUYZ-yGXXxIbQvCsDE8atI',
    appId: '1:593840566794:android:5b9375e8792f72805665f3',
    messagingSenderId: '593840566794',
    projectId: 'yello-18a1e',
    storageBucket: 'yello-18a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqSlIqN-6YnoWNoZ1GOkuf4xQwIMHX51w',
    appId: '1:593840566794:ios:e01d4edf349f71a45665f3',
    messagingSenderId: '593840566794',
    projectId: 'yello-18a1e',
    storageBucket: 'yello-18a1e.appspot.com',
    iosClientId:
        '593840566794-kc349eqfqtd9tm99nbmieh20h8tivke7.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqSlIqN-6YnoWNoZ1GOkuf4xQwIMHX51w',
    appId: '1:593840566794:ios:e01d4edf349f71a45665f3',
    messagingSenderId: '593840566794',
    projectId: 'yello-18a1e',
    storageBucket: 'yello-18a1e.appspot.com',
    iosClientId:
        '593840566794-kc349eqfqtd9tm99nbmieh20h8tivke7.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectu',
  );
}
